apiVersion: apps/v1
kind: Deployment
metadata:
  name: nearby-dispatch
  namespace: nearby-dispatch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nearby-dispatch
  template:
    metadata:
      labels:
        app: nearby-dispatch
    spec:
      containers:
        - name: nearby-dispatch
          image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/nearby-dispatch-system:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE

            - name: DB_HOST
              value: ""       # placeholder

            - name: DB_PORT
              value: "3306"

            - name: DB_NAME
              value: "nearby_dispatch"

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
