apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: nearby-dispatch
type: Opaque
data:
  DB_USERNAME: YWRtaW4=            # base64(admin)
  DB_PASSWORD: cGFzc3dvcmQ=        # base64(password)
