apiVersion: v1
kind: service
metadata:
  name: nearby-dispatch-service
  namespace: nearby-dispatch
spec:
   type: LoadBalancer
   selector:
     app: nearby-dispatch
   ports:
     - port: 80
       targetPort: 8080
